Repository Icinga/icingadb-web, pull requests merged in 2021-10, with the labels that each got.

#387 Add default path to icon img if no relative path has been specified
  library/Icingadb/Widget/ItemList/StateListItem.php
Labels: bug, cla/signed

#374 Add missing status details
  application/controllers/HostController.php
  application/controllers/ServiceController.php
  library/Icingadb/Widget/ItemList/BaseHistoryListItem.php
  library/Icingadb/Widget/ItemList/HostDetailHeader.php
  library/Icingadb/Widget/ItemList/HostList.php
  library/Icingadb/Widget/ItemList/HostListItemDetailed.php
  library/Icingadb/Widget/ItemList/ServiceDetailHeader.php
  library/Icingadb/Widget/ItemList/ServiceList.php
  library/Icingadb/Widget/ItemList/ServiceListItemDetailed.php
  library/Icingadb/Widget/StateChange.php
  public/css/widget/state-change.less
Labels: bug, area/ui, cla/signed

#383 Allow `host.user.name` and `host.usergroup.name` as well as `service...` in restrictions
  doc/04-Security.md
  library/Icingadb/Common/Auth.php
  library/Icingadb/Model/Behavior/ReRoute.php
  library/Icingadb/Model/Host.php
  library/Icingadb/Model/Service.php
  library/Icingadb/Web/Control/SearchBar/ObjectSuggestions.php
Labels: enhancement, cla/signed, area/access-control

#371 Use EventDetailExtentionHook in EventDetail
  library/Icingadb/Widget/Detail/EventDetail.php
Labels: bug, cla/signed

#338 Fix downtime progress bar bubble overflow
  library/Icingadb/Widget/Detail/CheckStatistics.php
  library/Icingadb/Widget/Detail/DowntimeCard.php
  public/css/mixin/progress-bar.less
  public/css/widget/check-statistics.less
Labels: bug, cla/signed
