Repository Icinga/icingadb-web, pull requests merged in 2021-12, with the labels that each got.

#468 Fix undefined array key `HTTP_USER_AGENT`
  configuration.php
Labels: cla/signed

#457 Use font-awesome icons if icon_image exists without extension
  library/Icingadb/Widget/ItemList/StateListItem.php
Labels: bug, cla/signed, area/representation

#470 Fix incorrect description in comment detail
  library/Icingadb/Widget/Detail/CommentDetail.php
Labels: bug, cla/signed, area/representation

#460 ApiTransportForm: Don't use text to create password elements
  application/forms/ApiTransportForm.php
Labels: bug, cla/signed, area/configuration
