Repository Icinga/icingadb-web, pull requests merged in 2021-05, with the labels that each got.

#177 Route blacklist
  application/controllers/HostgroupController.php
  application/controllers/HostgroupsController.php
  application/controllers/ServicegroupController.php
  application/controllers/ServicegroupsController.php
  application/controllers/UserController.php
  application/controllers/UsergroupController.php
  application/controllers/UsergroupsController.php
  application/controllers/UsersController.php
  configuration.php
  library/Icingadb/Common/Auth.php
  library/Icingadb/Web/Controller.php
  library/Icingadb/Widget/Detail/ObjectDetail.php
Labels: enhancement

#197 Fix action and note url labels
  library/Icingadb/Compat/CompatService.php
  library/Icingadb/Widget/Detail/ObjectDetail.php
  public/css/widget/actions.less
Labels: area/ui, bug

#199 Ensure to apply the user's default limit
  library/Icingadb/Web/Controller.php
Labels: bug

#195 Add object inspection
  application/controllers/HostController.php
  application/controllers/ServiceController.php
  configuration.php
  library/Icingadb/Command/IcingaApiCommand.php
  library/Icingadb/Command/Object/GetObjectCommand.php
  library/Icingadb/Command/Renderer/IcingaApiCommandRenderer.php
  library/Icingadb/Command/Transport/ApiCommandTransport.php
  library/Icingadb/Command/Transport/CommandTransport.php
  library/Icingadb/Common/Links.php
  library/Icingadb/Common/ObjectInspectionDetail.php
  library/Icingadb/Widget/Detail/HostInspectionDetail.php
  library/Icingadb/Widget/Detail/ServiceInspectionDetail.php
  public/css/common.less
  public/css/widget/object-inspection.less
Labels: enhancement

#196 Add missing host info
  application/controllers/HostController.php
  library/Icingadb/Widget/Detail/HostMetaInfo.php
  public/css/common.less
  public/css/widget/host-meta-info.less
Labels: bug

#183 Add health hooks
  library/Icingadb/ProvidedHook/IcingaHealth.php
  library/Icingadb/ProvidedHook/RedisHealth.php
  run.php
Labels: enhancement

#182 Feature/view mode switcher post
  application/controllers/CommentsController.php
  application/controllers/DowntimesController.php
  application/controllers/HostsController.php
  application/controllers/ServicesController.php
  library/Icingadb/Web/Controller.php
  library/Icingadb/Widget/ViewModeSwitcher.php
  public/css/widget/view-mode-switcher.less
Labels: enhancement
