Repository Icinga/icingadb-web, pull requests merged in 2021-11, with the labels that each got.

#400 Test: Add Macros unit tests
  test/php/library/Icingadb/Common/MacrosTest.php
Labels: cla/signed

#399 Add service id and host ids gridcols to pivotTable
  application/controllers/ServicesController.php
Labels: bug, cla/signed

#402 Macros: Fix return type mismatch
  library/Icingadb/Common/Macros.php
Labels: bug, cla/signed

#396 CSS: Align state-change soft-state-balls
  public/css/widget/state-change.less
Labels: area/ui, cla/signed

#414 common.less: Add margin-bottom to `.search-suggestions` class
  public/css/common.less
Labels: area/ui, cla/signed

#397 Add Overview, Problems and History menu when monitoring module is disabled
  configuration.php
  library/Icingadb/Web/Navigation/Renderer/ProblemsBadge.php
  library/Icingadb/Web/Navigation/Renderer/TotalProblemsBadge.php
  public/css/widget/state-badge.less
Labels: enhancement, cla/signed

#372 Use css variables for colors
  public/css/common.less
  public/css/list/action-list.less
  public/css/list/downtime-list.less
  public/css/list/item-list.less
  public/css/list/item-table.less
  public/css/list/list-item.less
  public/css/markdown.less
  public/css/mixin/progress-bar.less
  public/css/view/service-grid.less
  public/css/widget/actions.less
  public/css/widget/cancel-button.less
  public/css/widget/check-attempt.less
  public/css/widget/check-statistics.less
  public/css/widget/comment-popup.less
  public/css/widget/downtime-card.less
  public/css/widget/migrate-popup.less
  public/css/widget/monitoring-health.less
  public/css/widget/object-features.less
  public/css/widget/object-meta-info.less
  public/css/widget/object-statistics.less
  public/css/widget/performance-data-table.less
  public/css/widget/quick-actions.less
  public/css/widget/state-badge.less
  public/css/widget/state-change.less
  public/css/widget/tag-list.less
  public/css/widget/view-mode-switcher.less
Labels: cla/signed

#416 Discard invalid legacy url params
  library/Icingadb/Compat/UrlMigrator.php
Labels: bug, cla/signed

#408 Redesign migrate popup
  public/css/widget/migrate-popup.less
Labels: area/ui, cla/signed

#393 Vertical list show more redesign
  library/Icingadb/Widget/ItemList/PageSeparatorItem.php
  public/css/list/item-list.less
Labels: area/ui, cla/signed, area/navigation

#409 Bugfix/mobile issues 401
  library/Icingadb/Common/HostLink.php
  library/Icingadb/Common/ServiceLink.php
  public/css/list/comment-list.less
  public/css/widget/donut-container.less
  public/css/widget/monitoring-health.less
Labels: bug, area/ui, cla/signed

#413 Fix theme issues
  public/css/common.less
  public/css/mixin/progress-bar.less
  public/css/mixin/state-badges.less
  public/css/widget/object-meta-info.less
  public/css/widget/performance-data-table.less
  public/css/widget/state-badge.less
  public/css/widget/state-change.less
Labels: area/ui, cla/signed

#419 Display a proper success message when toggling object passive checks
  application/forms/Command/Object/ToggleObjectFeaturesForm.php
Labels: bug, cla/signed

#415 Return type fixes
  library/Icingadb/Command/Object/ProcessCheckResultCommand.php
  library/Icingadb/Command/Transport/ApiCommandTransport.php
  library/Icingadb/Command/Transport/CommandTransport.php
  library/Icingadb/Common/HostStates.php
  library/Icingadb/Common/ObjectInspectionDetail.php
  library/Icingadb/Common/ServiceStates.php
  library/Icingadb/ProvidedHook/IcingaHealth.php
  library/Icingadb/Web/Navigation/Renderer/ProblemsBadge.php
  library/Icingadb/Widget/Detail/CheckStatistics.php
  library/Icingadb/Widget/Detail/HostDetail.php
  library/Icingadb/Widget/Detail/ServiceDetail.php
  library/Icingadb/Widget/ItemList/BaseHistoryListItem.php
  library/Icingadb/Widget/ItemList/StateListItem.php
Labels: bug, cla/signed

#427 Don't fail if the problems badge is null
  configuration.php
  library/Icingadb/Web/Navigation/Renderer/ProblemsBadge.php
Labels: bug, cla/signed

#426 Use the empty string for probing the Icinga 2 API
  library/Icingadb/Command/Transport/ApiCommandTransport.php
Labels: bug, cla/signed

#432 Controller: Only keep preserved params for the searchbar action
  library/Icingadb/Web/Controller.php
Labels: bug, cla/signed, area/controls

#436 configuration.php: Add missing description for icingadb overview
  configuration.php
Labels: bug, cla/signed

#434 Fix Column 'host_id' in where clause is ambiguous
  application/controllers/HostController.php
Labels: cla/signed

#395 add option to use icingadb as backend
  application/controllers/ConfigController.php
  application/controllers/MigrateController.php
  application/forms/SetAsBackendConfigForm.php
  application/forms/SetAsBackendForm.php
  configuration.php
  library/Icingadb/Hook/IcingadbSupportHook.php
  public/css/widget/migrate-popup.less
  public/js/migrate.js
Labels: cla/signed

#406 Implement schema command_id prefix change
  library/Icingadb/Model/Checkcommand.php
  library/Icingadb/Model/CheckcommandArgument.php
  library/Icingadb/Model/CheckcommandCustomvar.php
  library/Icingadb/Model/CheckcommandEnvvar.php
  library/Icingadb/Model/Eventcommand.php
  library/Icingadb/Model/EventcommandArgument.php
  library/Icingadb/Model/EventcommandCustomvar.php
  library/Icingadb/Model/EventcommandEnvvar.php
  library/Icingadb/Model/Notification.php
  library/Icingadb/Model/Notificationcommand.php
  library/Icingadb/Model/NotificationcommandArgument.php
  library/Icingadb/Model/NotificationcommandCustomvar.php
  library/Icingadb/Model/NotificationcommandEnvvar.php
Labels: cla/signed

#448 Set default value of mixed type feature commands of multi-selected hosts or services to "noop".
  application/forms/Command/Object/ToggleObjectFeaturesForm.php
Labels: bug, cla/signed

#449 Fix dis/enabling of feature commands of multi-selected hosts or services.
  application/forms/Command/Object/ToggleObjectFeaturesForm.php
Labels: bug, cla/signed

#445 IcingadbSupportHook: Rename method to `isIcingaDbSetAsPreferredBackend()`
  library/Icingadb/Hook/IcingadbSupportHook.php
Labels: bug, cla/signed

#450 Fix incorrect filter columns in list footers
  library/Icingadb/Common/StateBadges.php
  library/Icingadb/Widget/HostStateBadges.php
  library/Icingadb/Widget/ServiceStateBadges.php
Labels: bug, cla/signed

#452 Fix incorrect assignment of class handled to the service badges in service grid.
  application/views/scripts/services/grid-flipped.phtml
  application/views/scripts/services/grid.phtml
Labels: bug, cla/signed, area/view

#454 Use display names as axis headers for hosts and services in service grid.
  application/controllers/ServicesController.php
Labels: bug, cla/signed, area/view

#442 Fix too extensive host notification recipients
  library/Icingadb/Widget/Detail/ObjectDetail.php
Labels: bug, cla/signed

#421 Downtime: Use new duration columns and clean up widgets
  library/Icingadb/Model/Downtime.php
  library/Icingadb/Model/DowntimeHistory.php
  library/Icingadb/Widget/Detail/DowntimeDetail.php
  library/Icingadb/Widget/ItemList/BaseDowntimeListItem.php
Labels: cla/signed

#405 Optimize queries
  application/controllers/CommentsController.php
  application/controllers/DowntimesController.php
  application/controllers/HistoryController.php
  application/controllers/HostController.php
  application/controllers/HostsController.php
  application/controllers/ServiceController.php
  application/controllers/ServicesController.php
  library/Icingadb/Model/Downtime.php
Labels: cla/signed

#465 ApiTransportForm: Fix force creation of a transport doesn't work
  application/forms/ApiTransportForm.php
Labels: bug, cla/signed, area/configuration
