Repository Icinga/icingadb-web, pull requests merged in 2021-08, with the labels that each got.

#206 Align all controls on the same baseline
  library/Icingadb/Widget/ShowMore.php
  public/css/common.less
  public/css/list/comment-list.less
  public/css/list/downtime-list.less
  public/css/list/item-list.less
  public/css/list/list-item.less
  public/css/list/user-list.less
  public/css/widget/host-meta-info.less
  public/css/widget/object-statistics.less
  public/css/widget/quick-actions.less
  public/css/widget/view-mode-switcher.less
Labels: area/ui, bug

#204 Add Service Grid
  application/controllers/ServicesController.php
  application/views/scripts/joystickPagination-icingadb.phtml
  application/views/scripts/services/grid-flipped.phtml
  application/views/scripts/services/grid.phtml
  configuration.php
  library/Icingadb/Data/PivotTable.php
  library/Icingadb/Web/Control/ProblemToggle.php
  public/css/common.less
  public/css/view/service-grid.less
Labels: area/ui, cla/signed, enhancement

#228 Remove redudant titles
  library/Icingadb/Widget/Detail/HostDetail.php
  library/Icingadb/Widget/Detail/ObjectDetail.php
Labels: area/ui, cla/signed, enhancement

#235 Show parent and triggered by downtime
  application/controllers/DowntimeController.php
  application/controllers/EventController.php
  library/Icingadb/Model/Downtime.php
  library/Icingadb/Model/DowntimeHistory.php
  library/Icingadb/Web/Control/SearchBar/ObjectSuggestions.php
  library/Icingadb/Widget/Detail/DowntimeDetail.php
  library/Icingadb/Widget/Detail/EventDetail.php
Labels: enhancement, cla/signed

#223 Optimize downtime list item titles
  library/Icingadb/Widget/ItemList/BaseDowntimeListItem.php
  public/css/list/item-list.less
Labels: bug, area/ui, cla/signed

#227 display user and usergroups customvars
  application/controllers/UserController.php
  application/controllers/UsergroupController.php
  library/Icingadb/Common/Links.php
  library/Icingadb/Widget/Detail/UserDetail.php
  library/Icingadb/Widget/Detail/UsergroupDetail.php
Labels: enhancement, cla/signed

#237 CSS: Apply the separation line to the list footer element
  public/css/common.less
Labels: bug, area/ui, cla/signed

#240 HostMetaInfo: Add dots instead of underscores
  library/Icingadb/Widget/Detail/HostMetaInfo.php
Labels: enhancement, cla/signed

#244 view-mode-switcher.less: Add pointer for view mode switcher
  public/css/widget/view-mode-switcher.less
Labels: enhancement, cla/signed

#243 Bugfix ObjectInspectionDetail::formatTimestamp()
  library/Icingadb/Common/ObjectInspectionDetail.php
Labels: bug, cla/signed

#246 Check and fix licence header
  library/Icingadb/Data/PivotTable.php
  library/Icingadb/Model/FlappingHistory.php
  library/Icingadb/ProvidedHook/X509/Sni.php
  library/Icingadb/Util/PerfData.php
  library/Icingadb/Util/PerfDataSet.php
  library/Icingadb/Util/ThresholdRange.php
  library/Icingadb/Web/Control/ProblemToggle.php
  library/Icingadb/Widget/PerfDataTable.php
Labels: cla/signed

#247 Drop unnecessary monitoring requirements
  library/Icingadb/Setup/ApiTransportPage.php
  library/Icingadb/Util/PerfData.php
Labels: cla/signed

#232 Native hooks
  application/controllers/HostController.php
  application/controllers/HostsController.php
  application/controllers/ServiceController.php
  application/controllers/ServicesController.php
  library/Icingadb/Compat/CompatPluginOutput.php
  library/Icingadb/Hook/ActionsHook/ObjectActionsHook.php
  library/Icingadb/Hook/Common/HookUtils.php
  library/Icingadb/Hook/EventDetailExtensionHook.php
  library/Icingadb/Hook/ExtensionHook/BaseExtensionHook.php
  library/Icingadb/Hook/ExtensionHook/ObjectDetailExtensionHook.php
  library/Icingadb/Hook/ExtensionHook/ObjectsDetailExtensionHook.php
  library/Icingadb/Hook/HostActionsHook.php
  library/Icingadb/Hook/HostDetailExtensionHook.php
  library/Icingadb/Hook/HostsDetailExtensionHook.php
  library/Icingadb/Hook/PluginOutputHook.php
  library/Icingadb/Hook/ServiceActionsHook.php
  library/Icingadb/Hook/ServiceDetailExtensionHook.php
  library/Icingadb/Hook/ServicesDetailExtensionHook.php
  library/Icingadb/Hook/TabHook.php
  library/Icingadb/Hook/TabHook/HookActions.php
  library/Icingadb/Hook/UserDetailExtensionHook.php
  library/Icingadb/Hook/UsergroupDetailExtensionHook.php
  library/Icingadb/Util/PluginOutput.php
  library/Icingadb/Widget/Detail/EventDetail.php
  library/Icingadb/Widget/Detail/HostDetail.php
  library/Icingadb/Widget/Detail/ObjectDetail.php
  library/Icingadb/Widget/Detail/ObjectsDetail.php
  library/Icingadb/Widget/Detail/ServiceDetail.php
  library/Icingadb/Widget/Detail/UserDetail.php
  library/Icingadb/Widget/Detail/UsergroupDetail.php
  library/Icingadb/Widget/HostListItemDetailed.php
  library/Icingadb/Widget/ItemList/BaseHistoryListItem.php
  library/Icingadb/Widget/ItemList/BaseNotificationListItem.php
  library/Icingadb/Widget/PluginOutputContainer.php
  library/Icingadb/Widget/ServiceListItemDetailed.php
  library/Icingadb/Widget/StateListItem.php
  run.php
Labels: enhancement, cla/signed

#225 Add icon image support
  application/controllers/HostController.php
  application/controllers/HostsController.php
  application/controllers/ServiceController.php
  application/controllers/ServicesController.php
  library/Icingadb/Widget/BaseItemList.php
  library/Icingadb/Widget/BaseListItem.php
  library/Icingadb/Widget/StateListItem.php
  public/css/list/item-list.less
  public/css/list/list-item.less
Labels: enhancement, cla/signed

#218 Feature: Increase limit on minimal view mode
  application/controllers/CommentsController.php
  application/controllers/DowntimesController.php
  application/controllers/HostgroupController.php
  application/controllers/HostsController.php
  application/controllers/ServicegroupController.php
  application/controllers/ServicesController.php
  library/Icingadb/Web/Controller.php
Labels: enhancement, cla/signed

#245 configuration.php: Add service grid icon
  configuration.php
Labels: bug, cla/signed

#236 Add scheduling source to the footer of check statistics
  library/Icingadb/Model/State.php
  library/Icingadb/Model/StateHistory.php
  library/Icingadb/Widget/Detail/CheckStatistics.php
  library/Icingadb/Widget/Detail/EventDetail.php
  public/css/widget/check-statistics.less
Labels: enhancement, cla/signed

#239 Use the same semi-infinite scrolling for the notification overview
  application/controllers/EventController.php
  application/controllers/HistoryController.php
  application/controllers/HostController.php
  application/controllers/NotificationsController.php
  application/controllers/ServiceController.php
  library/Icingadb/Common/LoadMore.php
  library/Icingadb/Widget/ItemList/HistoryList.php
  library/Icingadb/Widget/ItemList/NotificationList.php
Labels: enhancement, cla/signed

#253 Fix unknown column error in host service group details
  application/controllers/HostgroupController.php
  application/controllers/ServicegroupController.php
Labels: bug, cla/signed

#257 Controller: Fix missing `name` when switching view mode
  library/Icingadb/Web/Controller.php
Labels: bug, cla/signed

#254 Controller: Fix uncaught argument count error
  application/controllers/HistoryController.php
  application/controllers/HostController.php
  application/controllers/NotificationsController.php
  library/Icingadb/Web/Controller.php
Labels: bug, cla/signed

#275 Fix host service group detail cannot open with last comment
  application/controllers/HostgroupController.php
  application/controllers/ServicegroupController.php
  library/Icingadb/Model/Comment.php
Labels: bug, cla/signed

#282 Update requirements
  doc/02-Installation.md
  library/Icingadb/Setup/IcingaDbWizard.php
  module.info
Labels: bug, cla/signed, area/installation

#301 ObjectAuthorization: Escape RoleName when it consists of more than on…
  library/Icingadb/Authentication/ObjectAuthorization.php
Labels: bug, cla/signed, area/access-control

#305 ObjectAuthorization: Check whether the permission isn't within the re…
  library/Icingadb/Authentication/ObjectAuthorization.php
Labels: bug, cla/signed, area/access-control

#300 LoadMore: Don't reset page number on view mode change
  library/Icingadb/Common/LoadMore.php
Labels: bug, cla/signed, area/navigation

#312 Fix PDF export capability
  doc/02-Installation.md
  library/Icingadb/Common/BaseItemList.php
  library/Icingadb/Web/Controller.php
  library/Icingadb/Widget/Detail/ObjectDetail.php
  library/Icingadb/Widget/ItemList/StateListItem.php
  public/css/list/item-table.less
  public/css/list/list-item.less
Labels: bug, cla/signed, area/export

#311 `ApiTransportStep`: Fix commandtransport config not setup correctly
  library/Icingadb/Setup/ApiTransportStep.php
Labels: bug, cla/signed, area/installation

#313 Don't shift URL params to identify objects in detail views
  application/controllers/CommentController.php
  application/controllers/DowntimeController.php
  application/controllers/EventController.php
  application/controllers/HostController.php
  application/controllers/HostgroupController.php
  application/controllers/ServiceController.php
  application/controllers/ServicegroupController.php
  application/controllers/UserController.php
  application/controllers/UsergroupController.php
Labels: bug, cla/signed, area/navigation

#299 Support `ViewModeSwitcher` & `sortControl` in `Host/Service` history
  application/controllers/HostController.php
  application/controllers/ServiceController.php
Labels: bug, cla/signed, area/controls

#310 HealthController: Dis/enabling Fcmds globally doesn't apply changes i…
  application/controllers/HealthController.php
Labels: bug, cla/signed, area/navigation

#316 Fix that monitoring module is still loaded
  library/Icingadb/Web/Controller.php
  library/Icingadb/Widget/Detail/ObjectDetail.php
  run.php
Labels: bug, cla/signed, area/dependencies
