Repository Icinga/icingadb-web, pull requests merged in 2021-09, with the labels that each got.

#321 Fix that searching in servicegrid has no effect
  application/controllers/ServicesController.php
  application/views/scripts/services/grid-flipped.phtml
  application/views/scripts/services/grid.phtml
  library/Icingadb/Web/Control/ProblemToggle.php
Labels: bug, cla/signed, area/controls

#302 HostController: Add `sortControl` to services tab of host detail
  application/controllers/HostController.php
Labels: bug, cla/signed, area/controls

#307 Add `No items found` to controllers
  application/views/scripts/services/grid-flipped.phtml
  application/views/scripts/services/grid.phtml
  library/Icingadb/Common/LoadMore.php
  public/css/list/item-table.less
Labels: bug, area/ui, cla/signed

#324 EventDetail: Fix improper notification detail wording
  library/Icingadb/Widget/Detail/EventDetail.php
Labels: bug, cla/signed

#326 Set active state on list items after page refresh
  public/js/action-list.js
Labels: bug, cla/signed

#327 Make object header unclickable in detail view
  application/controllers/HostController.php
  application/controllers/ServiceController.php
Labels: bug, cla/signed, area/navigation

#330 Apply general detail styles with a single class
  library/Icingadb/Common/ObjectInspectionDetail.php
  library/Icingadb/Widget/Detail/CommentDetail.php
  library/Icingadb/Widget/Detail/DowntimeDetail.php
  library/Icingadb/Widget/Detail/EventDetail.php
  library/Icingadb/Widget/Detail/ObjectDetail.php
  library/Icingadb/Widget/Detail/UserDetail.php
  library/Icingadb/Widget/Detail/UsergroupDetail.php
  public/css/common.less
Labels: bug, area/ui, cla/signed

#331 Link preferred view mode with the current view
  library/Icingadb/Web/Controller.php
Labels: bug, cla/signed, area/controls

#334 Unselect the correct object
  public/js/action-list.js
Labels: bug, cla/signed

#336 Fix the alignment of the control separator of the columns
  public/css/list/item-list.less
Labels: bug, cla/signed

#315 Show a notification for every successful action
  application/controllers/CommandTransportController.php
  application/forms/Command/Instance/ToggleInstanceFeaturesForm.php
  application/forms/Command/Object/AcknowledgeProblemForm.php
  application/forms/Command/Object/AddCommentForm.php
  application/forms/Command/Object/DeleteCommentForm.php
  application/forms/Command/Object/DeleteDowntimeForm.php
  application/forms/Command/Object/ProcessCheckResultForm.php
  application/forms/Command/Object/RemoveAcknowledgementForm.php
  application/forms/Command/Object/ScheduleCheckForm.php
  application/forms/Command/Object/ScheduleHostDowntimeForm.php
  application/forms/Command/Object/ScheduleServiceDowntimeForm.php
  application/forms/Command/Object/SendCustomNotificationForm.php
  application/forms/Command/Object/ToggleObjectFeaturesForm.php
Labels: bug, cla/signed, area/navigation

#340 Fix progress bar bubble title for downtime starting in the future
  library/Icingadb/Widget/Detail/DowntimeCard.php
Labels: bug, cla/signed, area/representation

#343 Set active state on list items after refresh
  library/Icingadb/Common/BaseListItem.php
  library/Icingadb/Widget/ItemList/BaseCommentListItem.php
  library/Icingadb/Widget/ItemList/BaseDowntimeListItem.php
  library/Icingadb/Widget/ItemList/BaseHistoryListItem.php
  library/Icingadb/Widget/ItemList/BaseNotificationListItem.php
  library/Icingadb/Widget/ItemList/CommandTransportListItem.php
  library/Icingadb/Widget/ItemList/HistoryList.php
  library/Icingadb/Widget/ItemList/HostgroupList.php
  library/Icingadb/Widget/ItemList/HostgroupListItem.php
  library/Icingadb/Widget/ItemList/NotificationList.php
  library/Icingadb/Widget/ItemList/ServicegroupList.php
  library/Icingadb/Widget/ItemList/ServicegroupListItem.php
  library/Icingadb/Widget/ItemList/UserList.php
  library/Icingadb/Widget/ItemList/UserListItem.php
  library/Icingadb/Widget/ItemList/UsergroupList.php
  library/Icingadb/Widget/ItemList/UsergroupListItem.php
Labels: bug, cla/signed

#344 Properly display start_time and end_time of downtimes if they are NULL
  library/Icingadb/Widget/Detail/DowntimeDetail.php
Labels: bug, cla/signed, area/representation

#348 Fix `search-editor-opener` alignment
  public/css/common.less
Labels: bug, area/ui, cla/signed

#345 Update documentation
  README.md
  doc/01-About.md
  doc/02-Installation.md
  doc/03-Configuration.md
  doc/04-Security.md
  doc/10-Migration.md
  doc/res/continue-with-preview.png
  doc/res/modal-dialog-preview.png
  doc/res/searchbar-completion-preview.png
  doc/res/service-detail-preview.png
  doc/res/url-migration-preview.png
  doc/res/view-switcher-preview.png
Labels: enhancement, cla/signed, area/documentation

#309 UserDetail: Enhance user detail view
  library/Icingadb/Widget/Detail/UserDetail.php
  library/Icingadb/Widget/ItemList/UserListItem.php
Labels: bug, cla/signed

#333 Don't allow user to delete scheduled downtimes
  application/forms/Command/Object/DeleteDowntimeForm.php
  library/Icingadb/Model/Downtime.php
  public/css/widget/cancel-button.less
Labels: bug, cla/signed, area/representation

#337 Controller: Reset all params on form change
  library/Icingadb/Web/Controller.php
Labels: bug, cla/signed, area/controls

#362 Fix multiple redis connection attempts
  application/forms/RedisConfigForm.php
  library/Icingadb/Common/IcingaRedis.php
  library/Icingadb/Common/ObjectInspectionDetail.php
  library/Icingadb/Model/Behavior/VolatileState.php
  library/Icingadb/ProvidedHook/ApplicationState.php
  library/Icingadb/ProvidedHook/RedisHealth.php
  library/Icingadb/Setup/RedisPage.php
Labels: bug, cla/signed

#346 Fix view mode switching shows less items when using vertical pagination
  application/controllers/HistoryController.php
  application/controllers/HostController.php
  application/controllers/NotificationsController.php
  application/controllers/ServiceController.php
  library/Icingadb/Web/Controller.php
Labels: bug, cla/signed, area/controls

#370 Don't access `soft_state` property directly
  library/Icingadb/Model/HostState.php
  library/Icingadb/Model/ServiceState.php
Labels: cla/signed

#367 css: Remove z-index from footer
  public/css/common.less
Labels: area/ui, cla/signed

#368 Extend the width of the action list in the detail view
  public/css/common.less
Labels: bug, area/ui, cla/signed

#352 Better declare empty values
  library/Icingadb/Common/ObjectInspectionDetail.php
  library/Icingadb/Widget/Detail/CustomVarTable.php
  library/Icingadb/Widget/Detail/DowntimeDetail.php
  library/Icingadb/Widget/Detail/EventDetail.php
  library/Icingadb/Widget/Detail/HostMetaInfo.php
  library/Icingadb/Widget/Detail/PerfDataTable.php
  library/Icingadb/Widget/Detail/UserDetail.php
Labels: bug, cla/signed, area/representation

#382 Remove `scheduling_source` placeholder
  library/Icingadb/Model/State.php
  library/Icingadb/Model/StateHistory.php
Labels: cla/signed
