Repository Icinga/icingadb-web, pull requests merged in 2022-09, with the labels that each got.

#631 Replace deprecated hook `Icinga\Web\Hook` with `Icinga\Application\Hook`
  application/controllers/MigrateController.php
  library/Icingadb/Hook/ExtensionHook/ObjectDetailExtensionHook.php
  library/Icingadb/Hook/ExtensionHook/ObjectsDetailExtensionHook.php
  library/Icingadb/Hook/TabHook/HookActions.php
  library/Icingadb/Widget/Detail/ObjectDetail.php
Labels: bug, cla/signed

#558 Auth: Apply objects filter with `servicegroup.name` correctly
  library/Icingadb/Model/Behavior/ReRoute.php
  library/Icingadb/Model/Comment.php
  library/Icingadb/Model/Downtime.php
  library/Icingadb/Model/History.php
  library/Icingadb/Model/NotificationHistory.php
Labels: bug, cla/signed, area/access-control

#632 Make group summaries work in the SearchBar
  library/Icingadb/Model/Hostgroupsummary.php
  library/Icingadb/Model/ServicegroupSummary.php
Labels: bug, cla/signed

#628 Fix broken history if config is not synced yet
  library/Icingadb/Authentication/ObjectAuthorization.php
  library/Icingadb/Widget/Detail/EventDetail.php
  library/Icingadb/Widget/ItemList/BaseHistoryListItem.php
  library/Icingadb/Widget/ItemList/BaseNotificationListItem.php
Labels: bug, cla/signed

#634 css: Prevent scrollbars to appear if icon images are large
  public/css/list/item-list.less
Labels: bug, area/ui, cla/signed

#635 Change the order of handled state icons
  library/Icingadb/Widget/ItemList/StateListItem.php
Labels: cla/signed
