Repository Icinga/icingadb-web, pull requests merged in 2022-04, with the labels that each got.

#501 Utilize `previous_soft_state` column
  library/Icingadb/Common/ObjectInspectionDetail.php
  library/Icingadb/Model/HostState.php
  library/Icingadb/Model/ServiceState.php
  library/Icingadb/Model/State.php
  library/Icingadb/Widget/ItemList/BaseHistoryListItem.php
  library/Icingadb/Widget/ItemList/HostDetailHeader.php
  library/Icingadb/Widget/ItemList/ServiceDetailHeader.php
  library/Icingadb/Widget/ItemList/StateListItem.php
  library/Icingadb/Widget/StateChange.php
  public/css/common.less
  public/css/widget/state-change.less
Labels: cla/signed, area/representation

#517 Don't provide migrate.js when monitoring isn't enabled
  configuration.php
Labels: bug, cla/signed, area/javascript

#520 Stop using Resolver without a Query
  library/Icingadb/Redis/VolatileStateResults.php
  library/Icingadb/Web/Control/SearchBar/ObjectSuggestions.php
Labels: bug, cla/signed

#518 Auth: Force query optimization on union queries
  library/Icingadb/Common/Auth.php
Labels: bug, cla/signed, area/access-control

#524 ObjectSuggestions: Sort suggested values
  library/Icingadb/Web/Control/SearchBar/ObjectSuggestions.php
Labels: cla/signed

#528 Reset default limit for pdf exports
  library/Icingadb/Web/Controller.php
Labels: cla/signed

#525 Fix some primary key irregularities
  library/Icingadb/Model/ActionUrl.php
  library/Icingadb/Model/Host.php
  library/Icingadb/Model/IconImage.php
  library/Icingadb/Model/NotesUrl.php
  library/Icingadb/Model/Service.php
Labels: cla/signed
