Repository Icinga/icingadb-web, pull requests merged in 2022-02, with the labels that each got.

#485 Use a red background on focus for remove buttons
  public/css/common.less
Labels: bug, area/ui, cla/signed

#492 Always show the previous soft state in history list items
  library/Icingadb/Widget/ItemList/BaseHistoryListItem.php
Labels: bug, cla/signed, area/representation

#490 Cleanup var mixin usages
  public/css/common.less
  public/css/list/action-list.less
  public/css/list/downtime-list.less
  public/css/list/item-list.less
  public/css/list/item-table.less
  public/css/list/list-item.less
  public/css/markdown.less
  public/css/mixin/progress-bar.less
  public/css/view/service-grid.less
  public/css/widget/actions.less
  public/css/widget/cancel-button.less
  public/css/widget/check-attempt.less
  public/css/widget/check-statistics.less
  public/css/widget/comment-popup.less
  public/css/widget/downtime-card.less
  public/css/widget/migrate-popup.less
  public/css/widget/monitoring-health.less
  public/css/widget/object-features.less
  public/css/widget/object-meta-info.less
  public/css/widget/object-statistics.less
  public/css/widget/performance-data-table.less
  public/css/widget/quick-actions.less
  public/css/widget/state-badge.less
  public/css/widget/state-change.less
  public/css/widget/tag-list.less
  public/css/widget/view-mode-switcher.less
Labels: cla/signed

#497 IcingadbSupportHook.php: Try to get preferences only if user exists
  library/Icingadb/Hook/IcingadbSupportHook.php
Labels: cla/signed, area/framework

#481 Fix duplicate service history entries
  application/controllers/ServiceController.php
Labels: bug, cla/signed, area/representation

#499 Fix that target _blank links in list items are loaded by XHR
  public/js/action-list.js
Labels: bug, cla/signed, area/javascript

#498 view-mode-switcher: Optimize for theming
  public/css/widget/view-mode-switcher.less
Labels: area/ui, cla/signed

#503 Show hints for problem badges for Hosts and Services in nav bar
  library/Icingadb/Web/Navigation/Renderer/HostProblemsBadge.php
  library/Icingadb/Web/Navigation/Renderer/ProblemsBadge.php
  library/Icingadb/Web/Navigation/Renderer/ServiceProblemsBadge.php
Labels: enhancement, cla/signed

#502 Fix view mode switcher shows different mode than what is used
  library/Icingadb/Web/Control/ViewModeSwitcher.php
Labels: bug, cla/signed, area/representation

#504 PerfData: Render unkown UOMs as-is
  library/Icingadb/Util/PerfData.php
Labels: bug, cla/signed, area/representation
