Repository Icinga/icingadb-web, pull requests merged in 2022-10, with the labels that each got.

#630 Provide generic tts integration
  application/controllers/CommentController.php
  application/controllers/EventController.php
  library/Icingadb/Common/TicketLinks.php
  library/Icingadb/Widget/Detail/CommentDetail.php
  library/Icingadb/Widget/Detail/EventDetail.php
  library/Icingadb/Widget/Detail/ObjectDetail.php
  library/Icingadb/Widget/ItemList/BaseCommentListItem.php
  library/Icingadb/Widget/ItemList/BaseDowntimeListItem.php
  library/Icingadb/Widget/ItemList/BaseHistoryListItem.php
  library/Icingadb/Widget/ItemList/CommentList.php
  library/Icingadb/Widget/ItemList/DowntimeList.php
  library/Icingadb/Widget/ItemList/HistoryList.php
Labels: enhancement, cla/signed

#639 Still load legacy hooks in object details if monitoring is just disabled
  library/Icingadb/Widget/Detail/ObjectDetail.php
Labels: bug, cla/signed, area/framework

#649 Fix/SetApiTimeout
  library/Icingadb/Command/Transport/ApiCommandTransport.php
Labels: cla/signed

#641 ObjectDetail: Fix action and note url retrieval
  library/Icingadb/Widget/Detail/ObjectDetail.php
Labels: bug, cla/signed

#662 Avoid accessing non-existent last comment
  library/Icingadb/Widget/ItemList/HostListItemDetailed.php
  library/Icingadb/Widget/ItemList/ServiceListItemDetailed.php
Labels: bug, cla/signed

#661 Database: Only use `PDO::MYSQL_ATTR_INIT_COMMAND` for mysql connections
  library/Icingadb/Common/Database.php
Labels: bug, cla/signed

#660 action-list.js: Open subject links in a new window if requested
  public/js/action-list.js
Labels: bug, cla/signed, area/navigation
