Repository Icinga/icingadb-web, pull requests merged in 2022-11, with the labels that each got.

#666 Fix output not rendered yet
  library/Icingadb/Util/PluginOutput.php
  library/Icingadb/Widget/Detail/EventDetail.php
  library/Icingadb/Widget/ItemList/BaseHistoryListItem.php
  library/Icingadb/Widget/ItemList/BaseNotificationListItem.php
Labels: bug, cla/signed, area/view

#664 Fix that some comments cannot be deleted
  library/Icingadb/Widget/Detail/CommentDetail.php
  library/Icingadb/Widget/Detail/DowntimeDetail.php
Labels: bug, cla/signed

#668 EventDetail: Use `'UTC'` instead of `DateTimeZone::UTC`
  library/Icingadb/Widget/Detail/EventDetail.php
Labels: bug, cla/signed, area/view

#671 RedisConfigForm: Properly store password of 2nd redis
  application/forms/RedisConfigForm.php
Labels: bug, cla/signed, area/configuration

#673 RedisConfigForm: Properly clear empty sections/options
  application/forms/RedisConfigForm.php
Labels: bug, cla/signed, area/configuration

#685 CSS: Fix list item footer colors
  public/css/list/list-item.less
Labels: cla/signed
