Repository Icinga/icingadb-web, pull requests merged in 2022-06, with the labels that each got.

#548 DbResourcePage: Add postgres option to the select element
  library/Icingadb/Setup/DbResourcePage.php
Labels: cla/signed

#536 Adjust `ipl\Orm\Query::with()` usages
  application/controllers/HealthController.php
  application/controllers/HostController.php
  application/controllers/HostsController.php
  application/controllers/ServicesController.php
  application/controllers/TacticalController.php
  library/Icingadb/Authentication/ObjectAuthorization.php
  library/Icingadb/Common/Auth.php
  library/Icingadb/Data/PivotTable.php
  library/Icingadb/Model/HoststateSummary.php
  library/Icingadb/Model/ServicestateSummary.php
  library/Icingadb/Web/Navigation/Renderer/HostProblemsBadge.php
  library/Icingadb/Web/Navigation/Renderer/ServiceProblemsBadge.php
Labels: cla/signed

#550 Adjust to recent orm and web changes
  library/Icingadb/Common/SearchControls.php
  library/Icingadb/Model/AcknowledgementHistory.php
  library/Icingadb/Model/ActionUrl.php
  library/Icingadb/Model/Behavior/ReRoute.php
  library/Icingadb/Model/Checkcommand.php
  library/Icingadb/Model/CheckcommandArgument.php
  library/Icingadb/Model/CheckcommandEnvvar.php
  library/Icingadb/Model/Comment.php
  library/Icingadb/Model/CommentHistory.php
  library/Icingadb/Model/Downtime.php
  library/Icingadb/Model/DowntimeHistory.php
  library/Icingadb/Model/Endpoint.php
  library/Icingadb/Model/Environment.php
  library/Icingadb/Model/Eventcommand.php
  library/Icingadb/Model/EventcommandArgument.php
  library/Icingadb/Model/EventcommandEnvvar.php
  library/Icingadb/Model/FlappingHistory.php
  library/Icingadb/Model/History.php
  library/Icingadb/Model/Host.php
  library/Icingadb/Model/HostState.php
  library/Icingadb/Model/Hostgroup.php
  library/Icingadb/Model/IconImage.php
  library/Icingadb/Model/NotesUrl.php
  library/Icingadb/Model/Notification.php
  library/Icingadb/Model/NotificationHistory.php
  library/Icingadb/Model/Notificationcommand.php
  library/Icingadb/Model/NotificationcommandArgument.php
  library/Icingadb/Model/NotificationcommandEnvvar.php
  library/Icingadb/Model/Service.php
  library/Icingadb/Model/ServiceState.php
  library/Icingadb/Model/Servicegroup.php
  library/Icingadb/Model/StateHistory.php
  library/Icingadb/Model/Timeperiod.php
  library/Icingadb/Model/TimeperiodRange.php
  library/Icingadb/Model/User.php
  library/Icingadb/Model/Usergroup.php
  library/Icingadb/Model/Zone.php
  library/Icingadb/Web/Control/SearchBar/ObjectSuggestions.php
Labels: cla/signed

#537 Add columns support
  application/controllers/HostsController.php
  application/controllers/ServicesController.php
  doc/10-Migration.md
  library/Icingadb/Common/DetailActions.php
  library/Icingadb/Common/SearchControls.php
  library/Icingadb/Compat/UrlMigrator.php
  library/Icingadb/Data/CsvResultSet.php
  library/Icingadb/Data/JsonResultSet.php
  library/Icingadb/Model/Behavior/FlattenedObjectVars.php
  library/Icingadb/Model/Checkcommand.php
  library/Icingadb/Model/CustomvarFlat.php
  library/Icingadb/Model/Eventcommand.php
  library/Icingadb/Model/Host.php
  library/Icingadb/Model/Hostgroup.php
  library/Icingadb/Model/Notification.php
  library/Icingadb/Model/Notificationcommand.php
  library/Icingadb/Model/Service.php
  library/Icingadb/Model/Servicegroup.php
  library/Icingadb/Model/Timeperiod.php
  library/Icingadb/Model/User.php
  library/Icingadb/Model/Usergroup.php
  library/Icingadb/Model/Vars.php
  library/Icingadb/Web/Control/SearchBar/ObjectSuggestions.php
  library/Icingadb/Web/Control/ViewModeSwitcher.php
  library/Icingadb/Web/Controller.php
  library/Icingadb/Widget/IconImage.php
  library/Icingadb/Widget/ItemList/StateListItem.php
  library/Icingadb/Widget/ItemTable/BaseItemTable.php
  library/Icingadb/Widget/ItemTable/BaseRowItem.php
  library/Icingadb/Widget/ItemTable/HostItemTable.php
  library/Icingadb/Widget/ItemTable/HostRowItem.php
  library/Icingadb/Widget/ItemTable/ServiceItemTable.php
  library/Icingadb/Widget/ItemTable/ServiceRowItem.php
  library/Icingadb/Widget/ItemTable/StateItemTable.php
  library/Icingadb/Widget/ItemTable/StateRowItem.php
  public/css/common.less
  public/css/list/action-list.less
  public/css/list/item-table.less
  public/css/list/state-item-table.less
  public/css/list/state-row-item.less
  public/js/action-list.js
Labels: cla/signed

#546 Add `_name` suffix to columns referring to name
  library/Icingadb/Compat/CompatHost.php
  library/Icingadb/Compat/CompatService.php
  library/Icingadb/Compat/UrlMigrator.php
  library/Icingadb/Model/Host.php
  library/Icingadb/Model/Service.php
  library/Icingadb/Util/PluginOutput.php
  library/Icingadb/Widget/Detail/CheckStatistics.php
  library/Icingadb/Widget/Detail/EventDetail.php
  library/Icingadb/Widget/Detail/ObjectDetail.php
  library/Icingadb/Widget/Detail/QuickActions.php
  library/Icingadb/Widget/ItemList/BaseHistoryListItem.php
  library/Icingadb/Widget/ItemList/BaseNotificationListItem.php
Labels: cla/signed

#551 Change menu section list order
  configuration.php
Labels: cla/signed

#552 Fix service grid handled services badges
  application/views/scripts/services/grid-flipped.phtml
  application/views/scripts/services/grid.phtml
Labels: bug, cla/signed, area/representation

#553 Add hint to icingadb and redis health message
  library/Icingadb/ProvidedHook/IcingaHealth.php
  library/Icingadb/ProvidedHook/RedisHealth.php
Labels: enhancement, cla/signed

#557 Show host badges in objects-detail for multi-selected hosts
  library/Icingadb/Widget/Detail/ObjectsDetail.php
Labels: bug, cla/signed

#565 Don't use `columns()` of ipl/sql to specify columns to be selected
  library/Icingadb/Authentication/ObjectAuthorization.php
Labels: cla/signed

#564 Don't sort perfData which can't be visualized
  library/Icingadb/Widget/Detail/PerfDataTable.php
Labels: bug, cla/signed, area/representation

#554 Update documentation
  README.md
  configuration.php
  doc/01-About.md
  doc/02-Installation.md
  doc/02-Installation.md.d/01-Amazon-Linux.md
  doc/02-Installation.md.d/02-CentOS.md
  doc/02-Installation.md.d/03-Debian.md
  doc/02-Installation.md.d/04-RHEL.md
  doc/02-Installation.md.d/05-SLES.md
  doc/02-Installation.md.d/06-Ubuntu.md
  doc/02-Installation.md.d/07-From-Source.md
  doc/03-Configuration.md
  doc/04-Security.md
  doc/05-Upgrading.md
  doc/10-Migration.md
  doc/res/icingadb-architecture.png
  doc/res/icingadb-dashboard.png
  doc/res/icingadb-web.png
  library/Icingadb/Common/Auth.php
  library/Icingadb/Common/ObjectInspectionDetail.php
Labels: enhancement, cla/signed, area/documentation

#560 Add `check_` prefix to `attempt,timeout` columns in `*_state` tables
  library/Icingadb/Compat/CompatHost.php
  library/Icingadb/Compat/UrlMigrator.php
  library/Icingadb/Model/HostState.php
  library/Icingadb/Model/ServiceState.php
  library/Icingadb/Model/State.php
  library/Icingadb/Model/StateHistory.php
  library/Icingadb/Widget/Detail/CheckStatistics.php
  library/Icingadb/Widget/Detail/EventDetail.php
  library/Icingadb/Widget/ItemList/BaseHistoryListItem.php
  library/Icingadb/Widget/ItemList/StateListItem.php
  library/Icingadb/Widget/ItemTable/StateRowItem.php
Labels: cla/signed

#566 Redis: Apply volatile state results directly to the state model
  library/Icingadb/Redis/VolatileState.php
  library/Icingadb/Redis/VolatileStateResults.php
Labels: bug, cla/signed

#567 Handle redis errors gracefully
  application/controllers/HostgroupController.php
  application/controllers/ServicegroupController.php
  library/Icingadb/Redis/VolatileStateResults.php
  library/Icingadb/Widget/ItemList/StateList.php
  library/Icingadb/Widget/Notice.php
  public/css/common.less
  public/css/widget/notice.less
Labels: bug, cla/signed

#569 Docs/About: Remove link to license
  doc/01-About.md
Labels: cla/signed, area/documentation

#574 .mailmap: display me always as "Alexander A. Klimov <alexander.klimov@icinga.com>"
  .mailmap
Labels: cla/signed

#561 ApplicationState: Check the availability of `IcingaRedis` first
  library/Icingadb/ProvidedHook/ApplicationState.php
  library/Icingadb/ProvidedHook/RedisHealth.php
Labels: cla/signed
