Repository Icinga/icingadb-web, pull requests merged in 2022-07, with the labels that each got.

#593 README.md: Fix wrong latest doc link
  README.md
Labels: cla/signed

#591 Enhance column labels
  library/Icingadb/Model/AcknowledgementHistory.php
  library/Icingadb/Model/ActionUrl.php
  library/Icingadb/Model/Checkcommand.php
  library/Icingadb/Model/CheckcommandArgument.php
  library/Icingadb/Model/CheckcommandEnvvar.php
  library/Icingadb/Model/Comment.php
  library/Icingadb/Model/CommentHistory.php
  library/Icingadb/Model/Downtime.php
  library/Icingadb/Model/DowntimeHistory.php
  library/Icingadb/Model/Endpoint.php
  library/Icingadb/Model/Eventcommand.php
  library/Icingadb/Model/EventcommandArgument.php
  library/Icingadb/Model/EventcommandEnvvar.php
  library/Icingadb/Model/FlappingHistory.php
  library/Icingadb/Model/History.php
  library/Icingadb/Model/Host.php
  library/Icingadb/Model/HostState.php
  library/Icingadb/Model/Hostgroup.php
  library/Icingadb/Model/IconImage.php
  library/Icingadb/Model/NotesUrl.php
  library/Icingadb/Model/Notification.php
  library/Icingadb/Model/NotificationHistory.php
  library/Icingadb/Model/Notificationcommand.php
  library/Icingadb/Model/NotificationcommandArgument.php
  library/Icingadb/Model/NotificationcommandEnvvar.php
  library/Icingadb/Model/Service.php
  library/Icingadb/Model/ServiceState.php
  library/Icingadb/Model/Servicegroup.php
  library/Icingadb/Model/StateHistory.php
  library/Icingadb/Model/Timeperiod.php
  library/Icingadb/Model/TimeperiodRange.php
  library/Icingadb/Model/User.php
  library/Icingadb/Model/Usergroup.php
  library/Icingadb/Model/Zone.php
  library/Icingadb/Web/Control/SearchBar/ObjectSuggestions.php
Labels: cla/signed

#597 More column label enhancements
  library/Icingadb/Model/CheckcommandArgument.php
  library/Icingadb/Model/CheckcommandEnvvar.php
  library/Icingadb/Model/Eventcommand.php
  library/Icingadb/Model/EventcommandArgument.php
  library/Icingadb/Model/EventcommandEnvvar.php
  library/Icingadb/Model/NotificationcommandArgument.php
  library/Icingadb/Model/TimeperiodRange.php
  library/Icingadb/Model/User.php
Labels: cla/signed

#588 CheckStatistics: Add EmptyState
  library/Icingadb/Widget/Detail/CheckStatistics.php
Labels: bug, cla/signed, area/representation

#585 Show correct flapping event details
  library/Icingadb/Widget/ItemList/BaseHistoryListItem.php
Labels: bug, cla/signed

#582 Change `overflow` property to `overflow-x` in `performance-data-table` class
  public/css/widget/performance-data-table.less
Labels: bug, area/ui, cla/signed

#579 Show expiration time of comments in the comments list if it is set
  library/Icingadb/Widget/ItemList/BaseCommentListItem.php
Labels: bug, cla/signed, area/representation
