Repository Icinga/icingadb-web, pull requests merged in 2022-08, with the labels that each got.

#616 Don't strictly check whether `hGet` returns false
  library/Icingadb/Common/ObjectInspectionDetail.php
Labels: bug, cla/signed

#615 PerfDataFormat: Ensure not to use string values when formatting perfdata
  library/Icingadb/Util/PerfDataFormat.php
Labels: bug, cla/signed

#619 Fix acknowledgements registered before icingadb history recording
  library/Icingadb/Widget/Detail/EventDetail.php
  library/Icingadb/Widget/ItemList/BaseHistoryListItem.php
Labels: bug, cla/signed

#612 UrlMigrator: Lower filter values targeting enum types
  library/Icingadb/Compat/UrlMigrator.php
Labels: bug, cla/signed

#601 Preserve filters after clicking `Load More`
  application/controllers/HistoryController.php
  application/controllers/NotificationsController.php
Labels: bug, cla/signed, area/navigation

#614 Drop `view` param from show more urls in all index routes
  application/controllers/CommentsController.php
  application/controllers/DowntimesController.php
  application/controllers/HostgroupsController.php
  application/controllers/HostsController.php
  application/controllers/ServicegroupsController.php
  application/controllers/ServicesController.php
Labels: cla/signed

#598 Fix legacy hook integration
  library/Icingadb/Compat/CompatObject.php
  library/Icingadb/Widget/Detail/ObjectDetail.php
Labels: bug, cla/signed, area/framework

#599 Easy access to raw customvars in hooks
  library/Icingadb/Model/Host.php
  library/Icingadb/Model/Service.php
Labels: enhancement, cla/signed, area/framework

#605 Fix pending state balls
  library/Icingadb/Widget/ItemList/StateListItem.php
  public/css/widget/state-change.less
Labels: cla/signed

#626 Show warning health state badges
  library/Icingadb/ProvidedHook/IcingaHealth.php
Labels: bug, cla/signed

#624 StateListItem: Also don't show last state change if its zero
  library/Icingadb/Widget/ItemList/StateListItem.php
Labels: bug, cla/signed, area/representation

#625 ObjectInspectionDetail: Handle formatting errors gracefully
  library/Icingadb/Common/ObjectInspectionDetail.php
Labels: bug, cla/signed, area/view

#623 Fix incorrect hostgroup/servicegroup detail results
  application/controllers/HostgroupsController.php
  application/controllers/ServicegroupsController.php
  library/Icingadb/Web/Control/SearchBar/ObjectSuggestions.php
  library/Icingadb/Web/Controller.php
Labels: bug, cla/signed, area/navigation

#627 Fix incomplete search results
  application/controllers/ServicesController.php
  application/controllers/TacticalController.php
  configuration.php
  library/Icingadb/Model/ServicestateSummary.php
  library/Icingadb/Web/Controller.php
Labels: bug, cla/signed, area/navigation

#575 Sort also pie charts in detailed view mode
  library/Icingadb/Util/PerfDataSet.php
  library/Icingadb/Widget/Detail/PerfDataTable.php
Labels: bug, cla/signed, area/representation
