Repository Icinga/icingadb-web, pull requests merged in 2022-01, with the labels that each got.

#443 comment-list: Add missing space before "on" in title
  library/Icingadb/Web/Navigation/IcingadbHostAction.php
  library/Icingadb/Web/Navigation/IcingadbServiceAction.php
  public/css/common.less
  public/css/list/comment-list.less
Labels: bug, area/ui, cla/signed

#478 PerfDataTable: Don't double encode cell values
  library/Icingadb/Widget/Detail/PerfDataTable.php
Labels: bug, cla/signed, area/representation

#477 Fix that invalid perfdata breaks detail views
  library/Icingadb/Util/PerfData.php
  library/Icingadb/Util/PerfDataSet.php
Labels: bug, cla/signed, area/view

#484 Fix active row state persistency
  library/Icingadb/Common/DetailActions.php
  public/js/action-list.js
Labels: bug, cla/signed, area/javascript
