Repository Icinga/icingadb-web, pull requests merged in 2022-03, with the labels that each got.

#507 Add missing details in exported detail views
  application/controllers/HostController.php
  application/controllers/HostgroupController.php
  application/controllers/ServiceController.php
  application/controllers/ServicegroupController.php
  application/controllers/UserController.php
  application/controllers/UsergroupController.php
  library/Icingadb/Widget/Detail/CommentDetail.php
  library/Icingadb/Widget/Detail/DowntimeDetail.php
  library/Icingadb/Widget/Detail/HostDetail.php
  library/Icingadb/Widget/Detail/ObjectDetail.php
  library/Icingadb/Widget/Detail/ServiceDetail.php
  library/Icingadb/Widget/Detail/UserDetail.php
  library/Icingadb/Widget/Detail/UsergroupDetail.php
  public/css/common.less
Labels: bug, cla/signed, area/export

#510 Adjust calls to `CompatController::setTitle()`
  application/controllers/CommandTransportController.php
  application/controllers/CommentController.php
  application/controllers/CommentsController.php
  application/controllers/DowntimeController.php
  application/controllers/DowntimesController.php
  application/controllers/EventController.php
  application/controllers/HealthController.php
  application/controllers/HistoryController.php
  application/controllers/HostController.php
  application/controllers/HostgroupController.php
  application/controllers/HostgroupsController.php
  application/controllers/HostsController.php
  application/controllers/NotificationsController.php
  application/controllers/ServiceController.php
  application/controllers/ServicegroupController.php
  application/controllers/ServicegroupsController.php
  application/controllers/ServicesController.php
  application/controllers/TacticalController.php
  application/controllers/UserController.php
  application/controllers/UsergroupController.php
  application/controllers/UsergroupsController.php
  application/controllers/UsersController.php
Labels: cla/signed

#495 Introduce `Icinga\Module\Icingadb\Common\SearchControls`
  library/Icingadb/Common/SearchControls.php
  library/Icingadb/Web/Controller.php
Labels: cla/signed

#511 Remove `cancel-button` styles
  application/forms/Command/Object/DeleteCommentForm.php
  public/css/common.less
  public/css/widget/cancel-button.less
Labels: cla/signed

#516 Fix that command refusals don't override grants
  library/Icingadb/Authentication/ObjectAuthorization.php
Labels: bug, cla/signed, area/access-control

#509 FlattenedObjectVars: Ignore filters targeting another relation
  library/Icingadb/Model/Behavior/FlattenedObjectVars.php
Labels: bug, cla/signed

#496 Feature/allow redis password
  application/forms/RedisConfigForm.php
  library/Icingadb/Common/IcingaRedis.php
  library/Icingadb/Setup/RedisStep.php
Labels: enhancement, cla/signed, area/configuration
