Repository Icinga/icingadb-web, pull requests merged in 2023-05, with the labels that each got.

#734 `Pagination|History`: Reset query offset on page reload
  application/controllers/HistoryController.php
  application/controllers/NotificationsController.php
Labels: bug, cla/signed, area/navigation

#737 list-item.less: Do not show the comment popup transparently
  public/css/list/list-item.less
Labels: bug, area/ui, cla/signed

#746 Mention correct possible values for `icingadb/denylist/routes`
  doc/04-Security.md
Labels: bug, cla/signed, area/documentation

#747 Fix confusing `Downtime cancelled` header in event history list
  library/Icingadb/Widget/ItemList/BaseHistoryListItem.php
Labels: bug, cla/signed, area/representation

#751 ConfigController: Always check if the user has permissions
  application/controllers/ConfigController.php
Labels: bug, cla/signed, area/access-control

#752 Severity sort must also sort objects by `last_state_change` in descending
  application/controllers/HostsController.php
  application/controllers/ServicesController.php
Labels: bug, cla/signed, area/representation

#745 AcknowledgeProblemForm: Don't show datepicker if `expire` checkbox is unchecked
  application/forms/Command/Object/AcknowledgeProblemForm.php
  application/forms/Command/Object/AddCommentForm.php
Labels: bug, cla/signed, area/configuration

#720 Fix that repeated grafana graphs are not shown properly
  library/Icingadb/Compat/CompatHost.php
  library/Icingadb/Compat/CompatService.php
Labels: bug, cla/signed

#705 Fix that the dashboard loses selection
  public/js/action-list.js
Labels: bug, cla/signed, area/javascript

#749 CheckStatistics: Show `retry_interval` if object in `problem && soft_state`
  library/Icingadb/Widget/Detail/CheckStatistics.php
Labels: bug, cla/signed, area/representation

#754 Unset pagination parameters for service grid when `limit=0,0`
  application/controllers/ServicesController.php
  application/views/scripts/joystickPagination-icingadb.phtml
  application/views/scripts/services/grid-flipped.phtml
  application/views/scripts/services/grid.phtml
  library/Icingadb/Data/PivotTable.php
Labels: bug, cla/signed, area/view

#675 Ipl-html/SelectElement: Use `options` attr instead of `multiOptions`
  application/forms/Command/Object/ProcessCheckResultForm.php
  application/forms/Command/Object/ScheduleHostDowntimeForm.php
Labels: cla/signed

#750 ObjectAuthorization: Quote rolename containing `dot (.)` correctly
  library/Icingadb/Authentication/ObjectAuthorization.php
Labels: bug, cla/signed, area/access-control

#762 Fix that variable names with dots are interpreted as paths
  library/Icingadb/Model/CustomvarFlat.php
  library/Icingadb/Widget/Detail/ObjectDetail.php
Labels: bug, cla/signed, area/representation

#756 Enhance global search
  application/controllers/CommentsController.php
  application/controllers/DowntimesController.php
  application/controllers/HostsController.php
  application/controllers/ServicesController.php
  application/controllers/TacticalController.php
  application/controllers/UsergroupsController.php
  application/controllers/UsersController.php
  library/Icingadb/Model/Host.php
  library/Icingadb/Model/Hostgroup.php
  library/Icingadb/Model/Service.php
  library/Icingadb/Model/Servicegroup.php
  library/Icingadb/Model/User.php
  library/Icingadb/Model/Usergroup.php
  library/Icingadb/Web/Controller.php
Labels: bug, cla/signed, area/navigation

#753 Models: Use `MillisecondTimestamp` instead of `Timestamp` behavior
  library/Icingadb/Model/AcknowledgementHistory.php
  library/Icingadb/Model/Behavior/Timestamp.php
  library/Icingadb/Model/Comment.php
  library/Icingadb/Model/CommentHistory.php
  library/Icingadb/Model/Downtime.php
  library/Icingadb/Model/DowntimeHistory.php
  library/Icingadb/Model/FlappingHistory.php
  library/Icingadb/Model/History.php
  library/Icingadb/Model/Instance.php
  library/Icingadb/Model/NotificationHistory.php
  library/Icingadb/Model/State.php
  library/Icingadb/Model/StateHistory.php
  library/Icingadb/ProvidedHook/ApplicationState.php
  library/Icingadb/ProvidedHook/IcingaHealth.php
  library/Icingadb/ProvidedHook/RedisHealth.php
  library/Icingadb/Widget/Detail/CheckStatistics.php
  library/Icingadb/Widget/Detail/CommentDetail.php
  library/Icingadb/Widget/Detail/DowntimeCard.php
  library/Icingadb/Widget/Detail/DowntimeDetail.php
  library/Icingadb/Widget/Detail/EventDetail.php
  library/Icingadb/Widget/Detail/HostMetaInfo.php
  library/Icingadb/Widget/Detail/ObjectDetail.php
  library/Icingadb/Widget/Detail/ServiceMetaInfo.php
  library/Icingadb/Widget/Health.php
  library/Icingadb/Widget/ItemList/BaseCommentListItem.php
  library/Icingadb/Widget/ItemList/BaseDowntimeListItem.php
  library/Icingadb/Widget/ItemList/BaseHistoryListItem.php
  library/Icingadb/Widget/ItemList/BaseNotificationListItem.php
  library/Icingadb/Widget/ItemList/StateListItem.php
  library/Icingadb/Widget/ItemTable/StateRowItem.php
Labels: bug, cla/signed

#655 Add reporting hooks to DetailsAction
  library/Icingadb/ProvidedHook/CreateHostSlaReport.php
  library/Icingadb/ProvidedHook/CreateServiceSlaReport.php
  run.php
Labels: enhancement, cla/signed, area/framework

#653 Filter for notification command
  library/Icingadb/Model/NotificationHistory.php
  library/Icingadb/Web/Control/SearchBar/ObjectSuggestions.php
Labels: enhancement, cla/signed
