Repository Icinga/icingadb-web, pull requests merged in 2023-09, with the labels that each got.

#854 Use `ipl\Stdlib\iterable_value_first` to access the first item..
  application/forms/Command/Object/AcknowledgeProblemForm.php
  application/forms/Command/Object/AddCommentForm.php
  application/forms/Command/Object/ProcessCheckResultForm.php
  application/forms/Command/Object/RemoveAcknowledgementForm.php
  application/forms/Command/Object/ScheduleCheckForm.php
  application/forms/Command/Object/SendCustomNotificationForm.php
Labels: bug, cla/signed

#423 GitHub Actions: Add PHPStan
  .github/workflows/php.yml
  application/controllers/HostsController.php
  application/forms/RedisConfigForm.php
  library/Icingadb/Common/CommandActions.php
  library/Icingadb/Common/IcingaRedis.php
  library/Icingadb/Compat/CompatObject.php
  library/Icingadb/Compat/UrlMigrator.php
  library/Icingadb/Data/CsvResultSet.php
  library/Icingadb/Data/JsonResultSet.php
  library/Icingadb/Data/PivotTable.php
  library/Icingadb/Hook/ActionsHook/ObjectActionsHook.php
  library/Icingadb/Hook/CustomVarRendererHook.php
  library/Icingadb/Hook/ExtensionHook/ObjectDetailExtensionHook.php
  library/Icingadb/Hook/ExtensionHook/ObjectsDetailExtensionHook.php
  library/Icingadb/Model/CheckcommandArgument.php
  library/Icingadb/Model/CheckcommandCustomvar.php
  library/Icingadb/Model/CheckcommandEnvvar.php
  library/Icingadb/Model/HostState.php
  library/Icingadb/Model/ServiceState.php
  library/Icingadb/Model/State.php
  library/Icingadb/ProvidedHook/CreateHostsSlaReport.php
  library/Icingadb/ProvidedHook/CreateServicesSlaReport.php
  library/Icingadb/ProvidedHook/Reporting/SlaReport.php
  library/Icingadb/ProvidedHook/X509/Sni.php
  library/Icingadb/Redis/VolatileStateResults.php
  library/Icingadb/Util/PerfData.php
  library/Icingadb/Web/Control/GridViewModeSwitcher.php
  library/Icingadb/Web/Control/SearchBar/ObjectSuggestions.php
  library/Icingadb/Web/Control/ViewModeSwitcher.php
  library/Icingadb/Web/Controller.php
  library/Icingadb/Widget/Detail/CustomVarTable.php
  library/Icingadb/Widget/Detail/DowntimeCard.php
  library/Icingadb/Widget/Detail/ObjectDetail.php
  library/Icingadb/Widget/Detail/PerfDataTable.php
  library/Icingadb/Widget/ItemList/BaseHistoryListItem.php
  phpstan-baseline.neon
  phpstan.neon
Labels: cla/signed

#807 Apply `csp` to inline css style
  application/controllers/CommandTransportController.php
  library/Icingadb/Widget/Detail/CheckStatistics.php
  library/Icingadb/Widget/Detail/DowntimeCard.php
  public/css/common.less
Labels: enhancement, cla/signed

#853 IcingaDbWizard: Fix requirements
  application/forms/RedisConfigForm.php
  library/Icingadb/Setup/ApiTransportPage.php
  library/Icingadb/Setup/IcingaDbWizard.php
Labels: cla/signed

#863 Make command actions easier to use with curl
  application/forms/Command/CommandForm.php
  library/Icingadb/Common/CommandActions.php
Labels: enhancement, cla/signed

#847 Fix redis states not applied to exports
  library/Icingadb/Data/CsvResultSet.php
  library/Icingadb/Data/JsonResultSet.php
  library/Icingadb/Redis/VolatileStateResults.php
  phpstan-baseline.neon
Labels: bug, cla/signed, area/export

#857 Utilize `ipl\Web\Url::setFilter()` where applicable
  application/controllers/CommentsController.php
  application/controllers/DowntimesController.php
  application/controllers/HistoryController.php
  application/controllers/HostsController.php
  application/controllers/MigrateController.php
  application/controllers/NotificationsController.php
  application/controllers/ServicesController.php
  library/Icingadb/Common/StateBadges.php
  library/Icingadb/Compat/UrlMigrator.php
  library/Icingadb/Web/Controller.php
  library/Icingadb/Widget/Detail/CommentDetail.php
  library/Icingadb/Widget/Detail/DowntimeDetail.php
  library/Icingadb/Widget/Detail/HostStatistics.php
  library/Icingadb/Widget/Detail/MultiselectQuickActions.php
  library/Icingadb/Widget/Detail/ObjectsDetail.php
  library/Icingadb/Widget/Detail/ServiceStatistics.php
  library/Icingadb/Widget/HostSummaryDonut.php
  library/Icingadb/Widget/ItemTable/HostgroupGridCell.php
  library/Icingadb/Widget/ItemTable/ServicegroupGridCell.php
  library/Icingadb/Widget/ServiceSummaryDonut.php
  phpstan-baseline.neon
  test/php/library/Icingadb/Common/StateBadgesTest.php
Labels: cla/signed

#859 Allow to reset active db connection
  library/Icingadb/ProvidedHook/X509/Sni.php
Labels: enhancement, cla/signed

#871 Use `ipl\Web\EmptyStateBar` where applicable
  application/views/scripts/services/grid-flipped.phtml
  application/views/scripts/services/grid.phtml
  library/Icingadb/Widget/ItemTable/StateItemTable.php
  public/css/common.less
  public/css/list/state-item-table.less
Labels: cla/signed

#876 Update phpstan baseline config
  phpstan-baseline.neon
Labels: cla/signed

#880 Fix broken detail view refreshes
  public/js/action-list.js
Labels: bug, cla/signed, area/javascript

#882 migrate: Properly override url params
  application/controllers/MigrateController.php
  library/Icingadb/Compat/UrlMigrator.php
Labels: bug, cla/signed, area/navigation

#884 IcingaRedis: Don't throw in method `isUnavailable`
  library/Icingadb/Common/IcingaRedis.php
Labels: bug, cla/signed, area/view

#889 Controller: Preserve only selected search request parameters
  library/Icingadb/Web/Controller.php
Labels: bug, cla/signed, area/navigation

#891 Fix that the migration widget doesn't suggest updated search urls if the sort column/direction is changed
  application/controllers/MigrateController.php
  public/js/migrate.js
Labels: bug, cla/signed, area/javascript

#886 Transform compat `action` & `notes` url macros automatically
  library/Icingadb/Common/Macros.php
  library/Icingadb/Widget/Detail/ObjectDetail.php
Labels: enhancement, cla/signed

#893 ObjectDetail: Don't try to group the user query if it's not there
  library/Icingadb/Widget/Detail/ObjectDetail.php
  phpstan-baseline.neon
Labels: bug, cla/signed, area/view

#875 Enhance package installation & configuration docs
  doc/02-Installation.md
  doc/02-Installation.md.d/01-Amazon-Linux.md
  doc/02-Installation.md.d/02-CentOS.md
  doc/02-Installation.md.d/03-Debian.md
  doc/02-Installation.md.d/04-RHEL.md
  doc/02-Installation.md.d/05-SLES.md
  doc/02-Installation.md.d/06-Ubuntu.md
  doc/02-Installation.md.d/07-From-Source.md
  doc/02-Installation.md.d/From-Source.md
  doc/03-Configuration.md
Labels: enhancement, cla/signed, area/documentation

#895 doc: Add chapter `Automation`
  doc/09-Automation.md
Labels: enhancement, cla/signed, area/documentation
