Repository Icinga/icingadb-web, pull requests merged in 2023-07, with the labels that each got.

#642 Add class structure to js files
  public/js/action-list.js
  public/js/loadmore.js
  public/js/migrate.js
Labels: cla/signed, area/javascript

#678 Allow to optionally export total averages of sla reports
  library/Icingadb/ProvidedHook/Reporting/SlaReport.php
Labels: enhancement, cla/signed, area/sla-reporting

#768 Fix/hide footer when empty in detailed list items
  library/Icingadb/Widget/ItemList/HostListItemDetailed.php
  library/Icingadb/Widget/ItemList/ServiceListItemDetailed.php
  public/css/list/list-item.less
Labels: bug, area/ui, cla/signed

#360 Add keyboard navigation for lists
  library/Icingadb/Common/DetailActions.php
  library/Icingadb/Common/LoadMore.php
  public/css/common.less
  public/css/list/item-list.less
  public/js/action-list.js
  public/js/loadmore.js
Labels: enhancement, cla/signed

#804 Provide reporting hook for single host/service
  library/Icingadb/ProvidedHook/CreateHostSlaReport.php
  library/Icingadb/ProvidedHook/CreateHostsSlaReport.php
  library/Icingadb/ProvidedHook/CreateServiceSlaReport.php
  library/Icingadb/ProvidedHook/CreateServicesSlaReport.php
  run.php
Labels: cla/signed

#810 Fix minor `action-list.js` issues
  public/js/action-list.js
Labels: bug, cla/signed, area/javascript

#808 Fix `list-item` footer
  library/Icingadb/Widget/ItemList/HostListItemDetailed.php
  library/Icingadb/Widget/ItemList/ServiceListItemDetailed.php
  public/css/list/list-item.less
Labels: cla/signed

#811 Restore `StateBadge` and `StateBadges`
  library/Icingadb/Common/StateBadges.php
  library/Icingadb/Web/Navigation/Renderer/ProblemsBadge.php
  library/Icingadb/Widget/HostStateBadges.php
  library/Icingadb/Widget/ServiceStateBadges.php
  library/Icingadb/Widget/StateBadge.php
  public/css/mixin/state-badges.less
  public/css/widget/state-badge.less
  test/php/library/Icingadb/Common/StateBadgesTest.php
Labels: cla/signed

#813 UrlMigrator: Strip leading slashes from url paths to check
  library/Icingadb/Compat/UrlMigrator.php
Labels: bug, ref/IP, cla/signed, area/navigation

#803 Fix that unreachable hosts and services are not shown as such
  library/Icingadb/Common/HostStates.php
  library/Icingadb/Common/StateBadges.php
  library/Icingadb/Model/Hostgroupsummary.php
  library/Icingadb/Model/HoststateSummary.php
  library/Icingadb/Model/ServicegroupSummary.php
  library/Icingadb/Model/ServicestateSummary.php
  library/Icingadb/Model/State.php
  library/Icingadb/Widget/Detail/CheckStatistics.php
  library/Icingadb/Widget/HostSummaryDonut.php
  library/Icingadb/Widget/ItemList/HostDetailHeader.php
  library/Icingadb/Widget/ItemList/ServiceDetailHeader.php
  library/Icingadb/Widget/ItemList/StateListItem.php
  library/Icingadb/Widget/ItemTable/HostgroupGridCell.php
  library/Icingadb/Widget/ItemTable/ServicegroupGridCell.php
  public/css/mixin/progress-bar.less
  test/php/library/Icingadb/Common/StateBadgesTest.php
Labels: bug, cla/signed, area/representation
