Repository Icinga/icingadb-web, pull requests merged in 2023-08, with the labels that each got.

#829 IcingaRedis: Introduce `fetchHostState` and `fetchServiceState`..
  library/Icingadb/Common/IcingaRedis.php
  library/Icingadb/Redis/VolatileStateResults.php
Labels: cla/signed

#721 Improve performance of Icinga 2 API commands processed in bulk
  application/controllers/HostController.php
  application/controllers/ServiceController.php
  application/forms/Command/CommandForm.php
  application/forms/Command/Instance/ToggleInstanceFeaturesForm.php
  application/forms/Command/Object/AcknowledgeProblemForm.php
  application/forms/Command/Object/AddCommentForm.php
  application/forms/Command/Object/CheckNowForm.php
  application/forms/Command/Object/DeleteCommentForm.php
  application/forms/Command/Object/DeleteDowntimeForm.php
  application/forms/Command/Object/ProcessCheckResultForm.php
  application/forms/Command/Object/RemoveAcknowledgementForm.php
  application/forms/Command/Object/ScheduleCheckForm.php
  application/forms/Command/Object/ScheduleHostDowntimeForm.php
  application/forms/Command/Object/ScheduleServiceDowntimeForm.php
  application/forms/Command/Object/SendCustomNotificationForm.php
  application/forms/Command/Object/ToggleObjectFeaturesForm.php
  library/Icingadb/Command/Object/DeleteCommentCommand.php
  library/Icingadb/Command/Object/DeleteDowntimeCommand.php
  library/Icingadb/Command/Object/GetObjectCommand.php
  library/Icingadb/Command/Object/ObjectCommand.php
  library/Icingadb/Command/Object/ObjectsCommand.php
  library/Icingadb/Command/Object/ProcessCheckResultCommand.php
  library/Icingadb/Command/Object/RemoveAcknowledgementCommand.php
  library/Icingadb/Command/Object/ScheduleCheckCommand.php
  library/Icingadb/Command/Object/ToggleObjectFeatureCommand.php
  library/Icingadb/Command/Object/WithCommentCommand.php
  library/Icingadb/Command/Renderer/IcingaApiCommandRenderer.php
Labels: enhancement, cla/signed

#833 Fix broken source tab
  application/controllers/HostController.php
  application/controllers/ServiceController.php
  library/Icingadb/Command/Object/ObjectsCommand.php
Labels: bug, cla/signed

#835 BaseItemTable: Introduce layout modes
  library/Icingadb/Common/BaseItemTable.php
  library/Icingadb/Widget/ItemTable/HostgroupTable.php
  library/Icingadb/Widget/ItemTable/ServicegroupTable.php
  public/css/common.less
Labels: bug, cla/signed

#834 action-list.js: Support `key-navigation` for `table.action-list`
  public/js/action-list.js
Labels: bug, cla/signed, area/javascript

#755 History: Sort also by type by default
  application/controllers/HistoryController.php
  application/controllers/HostController.php
  application/controllers/ServiceController.php
  library/Icingadb/Model/History.php
Labels: enhancement, cla/signed, area/view

#843 action-list.js: Use `getAttribute` to get `href`
  public/js/action-list.js
Labels: bug, cla/signed, area/javascript

#846 ObjectInspectionDetail: Render 'n. a.' if $command is empty
  library/Icingadb/Common/ObjectInspectionDetail.php
Labels: bug, cla/signed, area/representation

#848 ObjectInspectionDetail: HtmlElement param #3 expects ValidHtml
  library/Icingadb/Common/ObjectInspectionDetail.php
Labels: bug, cla/signed

#828 Deprecate `StateBadge` class again
  library/Icingadb/Common/StateBadges.php
  library/Icingadb/Web/Navigation/Renderer/ProblemsBadge.php
  library/Icingadb/Widget/StateBadge.php
  public/css/widget/state-badge.less
Labels: cla/signed
