Repository Icinga/icingadb-web, pull requests merged in 2023-10, with the labels that each got.

#912 Don't use values from `customvar` table for all custom vars
  library/Icingadb/Model/CustomvarFlat.php
  test/php/library/Icingadb/Model/CustomvarFlatTest.php
Labels: bug, cla/signed

#904 Fix that some macros break the host detail
  library/Icingadb/Common/Macros.php
  test/php/library/Icingadb/Common/MacrosTest.php
Labels: bug, cla/signed, area/view

#907 README.md: Fix badge urls
  README.md
Labels: cla/signed

#908 CheckStatistics#assembleBody(): avoid divisions by 0
  library/Icingadb/Widget/Detail/CheckStatistics.php
Labels: bug, cla/signed, area/view

#906 Fix that the dashboard loses selection, again
  public/js/action-list.js
Labels: bug, cla/signed, area/javascript

#917 host/services: Make sure severity sort orders the same as anywhere else
  application/controllers/HostController.php
Labels: bug, cla/signed

#920 ObjectInspectionDetail: Render invalid states
  library/Icingadb/Common/ObjectInspectionDetail.php
Labels: cla/signed, area/representation
