Repository Icinga/icingadb-web, pull requests merged in 2023-06, with the labels that each got.

#766 (AddComment/AcknowledgeProblem)Form: Add validators to `expire_time` element
  application/forms/Command/Object/AcknowledgeProblemForm.php
  application/forms/Command/Object/AddCommentForm.php
Labels: bug, cla/signed

#767 Don't allow creating downtimes with flexible duration `0h0m`
  application/forms/Command/Object/ScheduleServiceDowntimeForm.php
Labels: bug, cla/signed

#773 Fix negative next check value when both active and passive checks are disabled
  library/Icingadb/Widget/Detail/CheckStatistics.php
  public/css/widget/check-statistics.less
Labels: enhancement, cla/signed, area/representation

#651 SlaReport: Breakdown into an hour view
  library/Icingadb/ProvidedHook/Reporting/SlaReport.php
Labels: enhancement, cla/signed, area/sla-reporting

#618 Introduce Total Host and Total Service SLA Report
  library/Icingadb/Hook/Common/TotalSlaReportUtils.php
  library/Icingadb/ProvidedHook/Reporting/TotalHostSlaReport.php
  library/Icingadb/ProvidedHook/Reporting/TotalServiceSlaReport.php
  run.php
Labels: enhancement, cla/signed, area/sla-reporting

#758 Add `CopyToClipboard` button to copy executed command in `Source` tab
  library/Icingadb/Common/ObjectInspectionDetail.php
  library/Icingadb/Widget/Detail/EventDetail.php
  library/Icingadb/Widget/Detail/ObjectDetail.php
Labels: enhancement, cla/signed

#355 Add `Host-/Servicegroup` grid views
  application/controllers/HostgroupsController.php
  application/controllers/ServicegroupsController.php
  library/Icingadb/Common/BaseTableRowItem.php
  library/Icingadb/Web/Control/GridViewModeSwitcher.php
  library/Icingadb/Web/Control/ViewModeSwitcher.php
  library/Icingadb/Web/Controller.php
  library/Icingadb/Widget/ItemTable/BaseHostGroupItem.php
  library/Icingadb/Widget/ItemTable/BaseServiceGroupItem.php
  library/Icingadb/Widget/ItemTable/GridCellLayout.php
  library/Icingadb/Widget/ItemTable/HostgroupGridCell.php
  library/Icingadb/Widget/ItemTable/HostgroupTable.php
  library/Icingadb/Widget/ItemTable/HostgroupTableRow.php
  library/Icingadb/Widget/ItemTable/ServicegroupGridCell.php
  library/Icingadb/Widget/ItemTable/ServicegroupTable.php
  library/Icingadb/Widget/ItemTable/ServicegroupTableRow.php
  library/Icingadb/Widget/ItemTable/TableRowLayout.php
  public/css/common.less
  public/css/list/item-table.less
  public/css/widget/group-grid.less
  public/css/widget/table-layout.less
Labels: enhancement, cla/signed, area/view

#783 Fix key-value formatting for json and csv result set
  library/Icingadb/Data/CsvResultSet.php
  library/Icingadb/Data/JsonResultSet.php
Labels: bug, area/export

#784 Avoid leakage of `state.check_commandline` to restricted users
  library/Icingadb/Common/Auth.php
  library/Icingadb/Redis/VolatileStateResults.php
Labels: bug, cla/signed

#777 Visualize that a check or downtime is running
  configuration.php
  library/Icingadb/Widget/Detail/CheckStatistics.php
  library/Icingadb/Widget/Detail/DowntimeCard.php
  library/Icingadb/Widget/Detail/HostMetaInfo.php
  library/Icingadb/Widget/ItemList/BaseDowntimeListItem.php
  library/Icingadb/Widget/ItemList/StateListItem.php
  public/css/common.less
  public/css/list/downtime-list.less
  public/css/mixin/progress-bar.less
  public/css/widget/check-statistics.less
  public/css/widget/downtime-card.less
  public/js/progress-bar.js
Labels: enhancement, cla/signed, area/representation

#787 Fix migration false positives
  application/controllers/MigrateController.php
  library/Icingadb/Compat/UrlMigrator.php
Labels: bug, cla/signed, area/javascript

#789 migrate.js: Decode urls prior comparison with migration results
  public/js/migrate.js
Labels: cla/signed

#790 CheckStatistics: Don't simulate running checks if they're overdue
  library/Icingadb/Widget/Detail/CheckStatistics.php
Labels: bug, cla/signed, area/view
