Repository Icinga/icingadb-web, pull requests merged in 2024-07, with the labels that each got.

#1032 JsonResultSetUtils: When query offset is null, Use 0 as default
  library/Icingadb/Data/JsonResultSetUtils.php
Labels: bug, cla/signed

#1031 UserDetail: add missing information
  application/controllers/UserController.php
  library/Icingadb/Model/User.php
  library/Icingadb/Widget/Detail/UserDetail.php
Labels: bug, cla/signed

#1026 PluginOutput::render(): Return correctly cut off output
  library/Icingadb/Util/PluginOutput.php
  phpstan-baseline-7x.neon
  phpstan-baseline-8x.neon
  phpstan-baseline-standard.neon
  test/php/library/Icingadb/Util/PluginOutputTest.php
Labels: bug, cla/signed

#1033 Configurable output limit
  doc/03-Configuration.md
  library/Icingadb/Widget/Detail/EventDetail.php
  library/Icingadb/Widget/Detail/ObjectDetail.php
  phpstan-baseline-standard.neon
Labels: cla/signed, area/configuration

#1005 Handle missing results more gracefully
  library/Icingadb/Common/TicketLinks.php
  library/Icingadb/Compat/CompatObject.php
  library/Icingadb/Redis/VolatileStateResults.php
  library/Icingadb/Widget/Detail/CheckStatistics.php
  library/Icingadb/Widget/Detail/EventDetail.php
  library/Icingadb/Widget/Detail/ObjectDetail.php
  library/Icingadb/Widget/Detail/ServiceMetaInfo.php
  library/Icingadb/Widget/ItemList/BaseHistoryListItem.php
  library/Icingadb/Widget/ItemTable/StateRowItem.php
  phpstan-baseline-standard.neon
Labels: cla/signed

#1034 Catch `\Throwable` when utilizing hooks
  library/Icingadb/Hook/ActionsHook/ObjectActionsHook.php
  library/Icingadb/Hook/CustomVarRendererHook.php
  library/Icingadb/Hook/ExtensionHook/ObjectDetailExtensionHook.php
  library/Icingadb/Hook/ExtensionHook/ObjectsDetailExtensionHook.php
  library/Icingadb/Hook/PluginOutputHook.php
  library/Icingadb/Hook/TabHook/HookActions.php
  library/Icingadb/Widget/Detail/ObjectDetail.php
Labels: cla/signed

#1036 DbResourcePage: Avoid showing a default charset for pgsql
  library/Icingadb/Setup/DbResourcePage.php
Labels: bug, cla/signed, area/installation

#1038 action-list: Take items with css propery `display:contents` into account
  public/js/action-list.js
Labels: bug, cla/signed, area/javascript
