Repository Icinga/icingadb-web, pull requests merged in 2024-10, with the labels that each got.

#1066 RedundancyGroupState: Add method `getStateText()`
  library/Icingadb/Model/RedundancyGroupState.php
Labels: cla/signed

#1062 Indicate the number of affected children by a particular parent
  library/Icingadb/Common/Icons.php
  library/Icingadb/Model/Host.php
  library/Icingadb/Model/HostState.php
  library/Icingadb/Model/Service.php
  library/Icingadb/Model/ServiceState.php
  library/Icingadb/Model/State.php
  library/Icingadb/Widget/ItemList/StateListItem.php
  public/css/common.less
Labels: enhancement, cla/signed, area/representation

#1057 Show root problem list for objects with problem and are part of dependency
  application/controllers/ServiceController.php
  library/Icingadb/Common/StateBadges.php
  library/Icingadb/Model/Behavior/HasProblematicParent.php
  library/Icingadb/Model/RedundancyGroupState.php
  library/Icingadb/Model/RedundancyGroupSummary.php
  library/Icingadb/Model/Service.php
  library/Icingadb/Model/UnreachableParent.php
  library/Icingadb/Redis/VolatileStateResults.php
  library/Icingadb/Widget/DependencyNodeStateBadges.php
  library/Icingadb/Widget/DependencyNodeStatistics.php
  library/Icingadb/Widget/Detail/HostDetail.php
  library/Icingadb/Widget/Detail/ObjectDetail.php
  library/Icingadb/Widget/Detail/ServiceDetail.php
  library/Icingadb/Widget/ItemList/DependencyNodeList.php
  library/Icingadb/Widget/ItemList/RedundancyGroupListItem.php
  library/Icingadb/Widget/ItemList/StateListItem.php
  public/css/common.less
  public/css/list/redundancy-group-list-item.less
  public/css/widget/dependency-node-state-badges.less
  test/php/library/Icingadb/Common/StateBadgesTest.php
Labels: enhancement, cla/signed

#1072 Show affected objects in the object detail for failed dependencies
  library/Icingadb/Widget/Detail/HostDetail.php
  library/Icingadb/Widget/Detail/ObjectDetail.php
  library/Icingadb/Widget/Detail/ServiceDetail.php
Labels: enhancement, cla/signed
