Repository Icinga/icingadb-web, pull requests merged in 2024-03, with the labels that each got.

#970 migrate/search-url: Prevent further false-positives
  application/controllers/MigrateController.php
Labels: bug, ref/IP, cla/signed

#971 Add document for the configuration of the IcingaDB-Modul
  doc/03-Configuration.md
  doc/10-Migration.md
Labels: bug, cla/signed, area/documentation

#946 CommandActions: Only respond with JSON if it's an API request
  library/Icingadb/Common/CommandActions.php
Labels: bug, cla/signed, area/navigation

#995 Fix incorrect url migrations
  library/Icingadb/Compat/UrlMigrator.php
Labels: bug, cla/signed

#996 Macros: Log the object where a macro is not found
  library/Icingadb/Common/Macros.php
  phpstan.neon
Labels: bug, cla/signed

#1000 Fix broken detail due to duplicate actions
  library/Icingadb/Web/Navigation/Action.php
Labels: bug, cla/signed, area/view

#987 Fix missing badge in problems menu
  library/Icingadb/Web/Navigation/Renderer/ProblemsBadge.php
Labels: bug, cla/signed

#994 Fix broken host and servicegroup quick search
  library/Icingadb/Model/Hostgroupsummary.php
  library/Icingadb/Model/ServicegroupSummary.php
Labels: bug, cla/signed

#986 Fix that the global search ignores route denylists
  configuration.php
Labels: bug, cla/signed, area/access-control

#989 Controller: Serve JSON if accepted
  library/Icingadb/Web/Controller.php
Labels: bug, cla/signed, area/export

#997 Do not show okay states as handled if the object is unreachable
  library/Icingadb/Widget/ItemList/HostDetailHeader.php
  library/Icingadb/Widget/ItemList/ServiceDetailHeader.php
  library/Icingadb/Widget/ItemList/StateListItem.php
  library/Icingadb/Widget/ItemTable/StateRowItem.php
  phpstan-baseline-standard.neon
Labels: bug, area/ui, cla/signed

#978 Transform custom variable filters as late as possible
  doc/02-Installation.md.d/From-Source.md
  library/Icingadb/Model/Behavior/FlattenedObjectVars.php
  library/Icingadb/Model/CustomvarFlat.php
  module.info
  phpstan-baseline-standard.neon
  test/php/library/Icingadb/Model/Behavior/FlattenedObjectVarsTest.php
Labels: bug, cla/signed

#985 Fix history exports
  library/Icingadb/Data/CsvResultSet.php
  library/Icingadb/Data/CsvResultSetUtils.php
  library/Icingadb/Data/JsonResultSet.php
  library/Icingadb/Data/JsonResultSetUtils.php
  library/Icingadb/Data/VolatileCsvResults.php
  library/Icingadb/Data/VolatileJsonResults.php
  library/Icingadb/Web/Controller.php
  phpstan-baseline-7x.neon
  phpstan-baseline-8x.neon
  phpstan-baseline-standard.neon
Labels: bug, cla/signed, area/export

#1002 Fix that custom variables with dots in their name are broken
  library/Icingadb/Model/Behavior/FlattenedObjectVars.php
  test/php/library/Icingadb/Model/Behavior/FlattenedObjectVarsTest.php
Labels: bug, cla/signed
