Repository Icinga/icingadb-web, pull requests merged in 2025-07, with the labels that each got.

#1239 RedundancyGroupDetail: Eliminate duplicate nodes
  library/Icingadb/Widget/Detail/RedundancyGroupDetail.php
Labels: bug, cla/signed, area/representation

#1238 Add missing `unreachable_parent` relation
  library/Icingadb/Model/Host.php
  library/Icingadb/Model/Service.php
Labels: bug, cla/signed, area/access-control, area/view

#1244 Move the `HostController::joinFix()` method to `DependencyNode`
  application/controllers/HostController.php
  library/Icingadb/Model/DependencyNode.php
Labels: cla/signed, area/framework

#1248 DependencyNode: Use static call to avoid unnecessary columns in case of summary query
  library/Icingadb/Model/DependencyNode.php
Labels: cla/signed

#1247 Auth: Apply filter/hosts and filter/services to dependency queries
  library/Icingadb/Common/Auth.php
Labels: cla/signed

#1255 Release v1.2.2
  CHANGELOG.md
  module.info
Labels: cla/signed
