Repository Icinga/icingadb-web, pull requests merged in 2025-04, with the labels that each got.

#1139 Fix/set api timeout also for actual api call
  AUTHORS
  library/Icingadb/Command/Transport/ApiCommandTransport.php
Labels: cla/signed

#1103 Fix typo in Model/Host and Model/Service
  library/Icingadb/Model/Host.php
  library/Icingadb/Model/Service.php
Labels: cla/signed

#1149 Host|ServiceState: Add missing definition for `scheduling_source`
  library/Icingadb/Model/HostState.php
  library/Icingadb/Model/ServiceState.php
Labels: cla/signed

#1121 Use severity as default sort
  application/controllers/HostController.php
  application/controllers/HostgroupsController.php
  application/controllers/HostsController.php
  application/controllers/ServicegroupsController.php
  application/controllers/ServicesController.php
Labels: enhancement, cla/signed

#1158 CSS: Invert affected children element
  public/css/common.less
Labels: cla/signed

#1156 Rename users and usergroups to contacts and contactgroups
  application/clicommands/MigrateCommand.php
  application/controllers/ContactController.php
  application/controllers/ContactgroupController.php
  application/controllers/ContactgroupsController.php
  application/controllers/ContactsController.php
  application/controllers/UserController.php
  application/controllers/UsergroupController.php
  application/controllers/UsergroupsController.php
  application/controllers/UsersController.php
  configuration.php
  doc/04-Security.md
  doc/10-Migration.md
  library/Icingadb/Common/Auth.php
  library/Icingadb/Common/Links.php
  library/Icingadb/Compat/UrlMigrator.php
  library/Icingadb/Model/NotificationHistory.php
  library/Icingadb/Model/Usergroup.php
  library/Icingadb/Web/Control/SearchBar/ObjectSuggestions.php
  library/Icingadb/Widget/Detail/EventDetail.php
  library/Icingadb/Widget/Detail/ObjectDetail.php
  library/Icingadb/Widget/Detail/UsergroupDetail.php
  library/Icingadb/Widget/ItemList/ObjectList.php
  test/php/application/clicommands/MigrateCommandTest.php
Labels: area/ui, cla/signed

#1167 Fix detail view links for services in flipped grid
  application/views/scripts/services/grid-flipped.phtml
Labels: cla/signed

#1171 Fix horizontal scroll-bar in object detail view
  library/Icingadb/Widget/Detail/DowntimeCard.php
  public/css/mixin/progress-bar.less
  public/css/widget/check-statistics.less
Labels: bug, cla/signed

#1175 Fix that detail extensions produce gaps
  library/Icingadb/Hook/ExtensionHook/ObjectDetailExtensionHook.php
  library/Icingadb/Hook/ExtensionHook/ObjectsDetailExtensionHook.php
  library/Icingadb/Widget/Detail/ObjectDetail.php
Labels: cla/signed
