Repository Icinga/icingadb-web, pull requests merged in 2025-06, with the labels that each got.

#1122 ObjectInspectionDetail: Show host/service templates
  library/Icingadb/Common/ObjectInspectionDetail.php
Labels: enhancement, cla/signed

#1087 CustomVarTable: Let the user fully collapse subgroups
  library/Icingadb/Widget/Detail/CustomVarTable.php
Labels: enhancement, cla/signed, area/framework

#1209 StateBadges: Actually render links for single badges
  library/Icingadb/Common/StateBadges.php
Labels: bug, cla/signed, area/navigation

#1211 css: Make sure redundancy group statistics fit
  public/css/item/redundancy-group.less
Labels: cla/signed

#1214 Models: Register the `to 1` relations first to display them first in the search suggestions
  library/Icingadb/Model/Host.php
  library/Icingadb/Model/Service.php
Labels: cla/signed

#1212 Show Icinga DB and Redis version in health
  library/Icingadb/Model/Instance.php
  library/Icingadb/ProvidedHook/IcingaHealth.php
  library/Icingadb/ProvidedHook/RedisHealth.php
  library/Icingadb/Widget/Health.php
Labels: cla/signed

#1217 ObjectList: Don't add non-supported multiselect url to member/children list items of RedundancyGroup
  library/Icingadb/Widget/ItemList/ObjectList.php
Labels: bug, cla/signed

#1216 EventRenderer: Fix `soft_state` event visual
  library/Icingadb/View/EventRenderer.php
Labels: bug, cla/signed

#1215 ObjectSuggestions: Prioritze Column suggestions and best suggestions
  library/Icingadb/Web/Control/SearchBar/ObjectSuggestions.php
Labels: cla/signed

#1228 IcingaHealth: Switch to critical in case Icinga DB is too old
  library/Icingadb/ProvidedHook/IcingaHealth.php
  library/Icingadb/Widget/Health.php
Labels: cla/signed
