Repository Icinga/icingadb-web, pull requests merged in 2025-05, with the labels that each got.

#1177 Predis: Use the newly introduced xread command/method
  library/Icingadb/Common/IcingaRedis.php
  module.info
Labels: cla/signed

#1180 (Host|Service)Controller: Reset the query offset for LoadMore list
  application/controllers/HostController.php
  application/controllers/ServiceController.php
Labels: bug, cla/signed, area/navigation

#1159 ObjectDetail: Properly format last_state_change for PDF
  library/Icingadb/Widget/Detail/ObjectDetail.php
Labels: bug, cla/signed, area/export

#1086 CustomVarRendererHook: Log an exception's message and location
  library/Icingadb/Hook/CustomVarRendererHook.php
Labels: bug, cla/signed, area/framework

#1179 Controllers: Use `paginationControl::getEmptyStateMessage()` to set list's message
  application/controllers/CommentsController.php
  application/controllers/ContactgroupsController.php
  application/controllers/ContactsController.php
  application/controllers/DowntimesController.php
  application/controllers/HostController.php
  application/controllers/HostgroupController.php
  application/controllers/HostgroupsController.php
  application/controllers/HostsController.php
  application/controllers/RedundancygroupController.php
  application/controllers/ServiceController.php
  application/controllers/ServicegroupController.php
  application/controllers/ServicegroupsController.php
  application/controllers/ServicesController.php
  library/Icingadb/Widget/ItemList/ObjectList.php
Labels: cla/signed

#1120 QuickActions: Hide `Process check` and `Notification` button when feature is disabled
  library/Icingadb/Widget/Detail/MultiselectQuickActions.php
  library/Icingadb/Widget/Detail/QuickActions.php
Labels: bug, cla/signed, area/controls

#1183 StateItemTable: Add missing property `$emptyStateMessage` and getter/setter
  library/Icingadb/Widget/ItemTable/StateItemTable.php
Labels: cla/signed

#1118 Macros: Add missing support for `DateTime` type macro
  library/Icingadb/Common/Macros.php
Labels: bug, cla/signed

#1173 ObjectSuggestion: Dynamically adjust columns and custom var suggestion limits
  library/Icingadb/Web/Control/SearchBar/ObjectSuggestions.php
Labels: cla/signed

#1165 Add support for redis acl/username and database selection
  application/forms/RedisConfigForm.php
  library/Icingadb/Common/IcingaRedis.php
Labels: enhancement, cla/signed, area/configuration

#1184 ObjectGrid: Add missing property `$emptyStateMessage` and getter/setter
  library/Icingadb/Widget/ItemTable/ObjectGrid.php
Labels: cla/signed

#1189 `Delete(Downtime|Comment)Form`: Fix the incorrect success message
  application/forms/Command/Object/DeleteCommentForm.php
  application/forms/Command/Object/DeleteDowntimeForm.php
Labels: bug, cla/signed

#1190 DependencyEdgeState: Add relation `edge`
  library/Icingadb/Model/DependencyEdgeState.php
Labels: cla/signed

#1198 Ellipsize plugin output in list items with common layout
  public/css/item/item-layout.less
Labels: cla/signed
